### ISSUE TITLE
Add a direction option so on vertical orientation values can be bottom-to-top.

### ISSUE THREAD

**Issue by cirilomegg** [danielcrisp/angular-rangeslider#44]
I need to add the slider but on vertical orientation with values from bottom-to-top. Currently it supports only top-to-bottom. Is it correct?

Update: I am able to workaround that by setting negative numbers for min/max/model-min but it would be nice to have an option to do that automatically.

```
<div range-slider
    min="-100"
    max="-30"
    model-min="model.zoomValue"
    orientation="vertical"
    on-handle-up="zoomChart()"
    pin-handle="max"
    show-values="false">
</div>
```

**Comment by knitzie** [comment]
+1

**Comment by JAlbizures** [comment]
+1

**Comment by dsifford** [comment]
How is this still even an issue? It is absolutely unfathomable why this was even released to the public like this...

**Comment by dsifford** [comment]
To those experiencing this issue -- Follow @cirilomegg 's instructions, and then add this css to your stylesheets to hide the negative sign.

```css
.ngrs-value.ngrs-value-min,
.ngrs-value.ngrs-value-max {
    width: 33px;
    margin-left:auto;
    margin-right:auto;
    text-align:right;
    overflow:hidden;
    white-space: nowrap;
}

.ngrs-value.ngrs-value-min > div,
.ngrs-value.ngrs-value-max > div {
  float:right;
  font-size: 1.2em;
  color: #333;
  font-weight: 600;
}
```
