### ISSUE TITLE
Suggestion: invisible hitbox for mobile.

### ISSUE THREAD

**Issue by TMeerhof** [danielcrisp/angular-rangeslider#46]
On mobile devices moving the sliders is difficult. An improvement would be to have an invisible ‘hitbox’ around the handles to improve the mobile user experience.

**Comment by sebastientromp** [comment]
+1 :)

**Comment by stefanwalther** [comment]
+1

**Comment by danielcrisp** [comment]
Have you tried using invisible borders? That's how I usually increase the 'hitbox' of an element...

```css
/* you can't just copy and paste this, its just an example */
.handle {
    border: 10px solid transparent;
}
```

Normally you'd need to fiddle with the markup a bit so it might not be possible with the default rangeslider template
